In [0]:
import numpy as np
import pandas as pd

In [0]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

In [0]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

In [0]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

In [0]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

In [0]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1)

In [0]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

In [0]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

In [0]:
feature = np.arange(6, 21)
print(feature)
label = 3*feature+4
print(label)

In [0]:
noise = np.random.uniform(low=-2.0, high=2.0, size=(15))
print (noise)
label = label + noise
print(label)

In [0]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

# Print the entire DataFrame
print(my_dataframe)

In [0]:
# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Print the entire DataFrame
print(my_dataframe)

In [0]:
print("Rows #0, #1, and #2:")
print(my_dataframe.head(3), '\n')

print("Row #2:")
print(my_dataframe.iloc[[2]], '\n')

print("Rows #1, #2, and #3:")
print(my_dataframe[1:4], '\n')

print("Column 'temperature':")
print(my_dataframe['temperature'])

In [36]:
my_data = np.array([[np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101)],
                 [np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101)],
                 [np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101)],
                 [np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101), np.random.randint(0, 101)]
])
#my_data = np.random.randint(low=0, high=101, size=(3, 4))
col_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

dataFrame = pd.DataFrame(columns=col_names, data=my_data)

#outputs the entire dataframe
print(dataFrame, '\n')

#outputs the value in the cell of row#1 of the Eleanor col
print("\nSecond row of the Eleanor column: %d\n" % dataFrame['Eleanor'][1])

#adds a fifth col Janet which is equal to the row by row sums of Tahani and Jason
dataFrame['Janet'] = dataFrame['Tahani'] + dataFrame['Jason']
print(dataFrame)

   Eleanor  Chidi  Tahani  Jason
0       77     82      32     61
1       34     41      92     18
2       67     38      74     78
3        8     61      66      7


Second row of the Eleanor column: 34

   Eleanor  Chidi  Tahani  Jason  Janet
0       77     82      32     61     93
1       34     41      92     18    110
2       67     38      74     78    152
3        8     61      66      7     73

In [0]:
data = np.random.randint(low=0, high=101, size=(3, 4))
col_names = ['Eleanor', 'Chidi', 'Tahani', 'Jason']

df = pd.DataFrame(columns=col_names, data=my_data)
# Create a reference by assigning my_dataframe to a new variable.
print("Experiment with a reference:")
reference_to_df = df

# Print the starting value of a particular cell.
print("  Starting value of : %d" % df['Jason'][1])
print("  Starting value of reference_to_df: %d\n" % reference_to_df['Jason'][1])

# Modify a cell in df.
df.at[1, 'Jason'] = df['Jason'][1] + 5
print("  Updated df: %d" % df['Jason'][1])
print("  Updated reference_to_df: %d\n\n" % reference_to_df['Jason'][1])

# Create a true copy of my_dataframe
print("Experiment with a true copy:")
copy_of_my_dataframe = my_dataframe.copy()

# Print the starting value of a particular cell.
print("  Starting value of my_dataframe: %d" % my_dataframe['activity'][1])
print("  Starting value of copy_of_my_dataframe: %d\n" % copy_of_my_dataframe['activity'][1])

# Modify a cell in df.
my_dataframe.at[1, 'activity'] = my_dataframe['activity'][1] + 3
print("  Updated my_dataframe: %d" % my_dataframe['activity'][1])
print("  copy_of_my_dataframe does not get updated: %d" % copy_of_my_dataframe['activity'][1])